name: Cypress - Serverest testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm i 
        run: npm ci

      - name: Start X virtual framebuffer (for running chrome)
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            choco install xvfb ; 
            Xvfb :99 -ac -screen 0 1920x1080x24 &
          fi

      - name: Run tests
        run: npm run cy:run:prod
